global:
  listening_port: 8080
  log_level: 0

sites:
  default:
    servers:
      - "http://localhost:8081"
      - "http://localhost:8082"
    check_period: 10s
  site2:
    servers:
      - "http://localhost:8083"
    check_period: 10s
    port: 5000
    domain: localhost
    path: "/folder"
